name: Build and Sign Giga Wall
on:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > release.keystore

      - name: Build & Sign Release
        run: ./gradlew bundleRelease assembleRelease
        env:
          MYAPP_RELEASE_STORE_FILE: release.keystore
          MYAPP_RELEASE_KEY_ALIAS: ${{ secrets.ALIAS }}
          MYAPP_RELEASE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          MYAPP_RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Giga-Wall-Production-Files
          path: |
            **/build/outputs/apk/release/*.apk
            **/build/outputs/bundle/release/*.aab
            
